dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install shellcheck
  - sudo apt-get -qq install libperl-critic-perl
  - sudo apt-get -qq install python-flake8
  - sudo apt-get -qq install flake8
script:
  - make test
